#ifndef NES_6502_H
#define NES_6502_H

/**
 * Cycle-level emulation interface for the NES RP2A03/6502 CPU.
 *
 * This header defines the CPU state, processor flags, binary data types,
 * and public interface used by the NES 6502 CPU emulator.
 *
 * The CPU is represented as an explicit machine state. Its registers,
 * bus state, instruction state, reset state, interrupt state, and OAM
 * DMA state are exposed through the CPU_6502 structure so that the
 * emulator can operate at cycle granularity.
 *
 * The implementation is provided by nes-6502.c.
 */

#ifndef NES_BIN_DATATYPES
#define NES_BIN_DATATYPES

#include <stdbool.h>
#include <stdint.h>

/**
 * Signed 8-bit integer.
 */
typedef int8_t byte;

/**
 * Signed 16-bit integer.
 */
typedef int16_t word;

/**
 * Unsigned 8-bit integer.
 */
typedef uint8_t ubyte;

/**
 * Unsigned 16-bit integer.
 */
typedef uint16_t uword;

/**
 * Unsigned counter used for cycle/step counts.
 */
typedef uint64_t counter;

#endif // NES_BIN_DATATYPES

/**
 * Negative flag.
 *
 * Set when the most significant bit of an arithmetic or logical result
 * is set.
 */
#define flag_n 0x80

/**
 * Overflow flag.
 *
 * Indicates signed arithmetic overflow.
 */
#define flag_v 0x40

/**
 * Unused flag.
 *
 * This bit is permanently high in the externally visible processor
 * status representation of the NES 6502.
 */
#define flag_u 0x20

/**
 * Break flag.
 *
 * Indicates a software interrupt request generated by the BRK instruction
 * when the processor status is pushed onto the stack.
 */
#define flag_b 0x10

/**
 * Decimal mode flag.
 *
 * Controls decimal arithmetic mode on a standard 6502. The NES CPU does
 * not implement decimal arithmetic, although the status bit remains part
 * of the processor status register.
 */
#define flag_d 0x08

/**
 * Interrupt-disable flag.
 *
 * When set, maskable IRQ interrupts are inhibited.
 */
#define flag_i 0x04

/**
 * Zero flag.
 *
 * Set when an arithmetic or logical operation produces a zero result.
 */
#define flag_z 0x02

/**
 * Carry flag.
 *
 * Represents the carry or borrow state of arithmetic operations and is
 * also used by several shift and rotate instructions.
 */
#define flag_c 0x01

/**
 * Complete state of the emulated NES 6502 CPU.
 *
 * CPU_6502 contains all state required to advance the processor one
 * clock at a time. The structure intentionally keeps architectural
 * state and internal emulation state together so that the CPU can be
 * inspected and debugged at cycle granularity.
 */
typedef struct CPU_6502 {
  /**
   * Number of CPU clock steps executed.
   */
  counter steps;

  /**
   * Processor registers.
   */
  struct reg {
    /**
     * Program counter.
     *
     * Contains the address of the next instruction or memory operation.
     */
    uword PC;

    /**
     * Accumulator register.
     */
    ubyte A;

    /**
     * X index register.
     */
    ubyte X;

    /**
     * Y index register.
     */
    ubyte Y;

    /**
     * Processor status register.
     *
     * Contains the N, V, U, B, D, I, Z, and C processor flags.
     */
    ubyte P;

    /**
     * Stack pointer.
     *
     * The 6502 stack occupies page $01 of CPU address space.
     */
    ubyte SP;
  } reg;

  /**
   * Current CPU bus state.
   *
   * Describes the address, value, and direction of the memory operation
   * requested by the CPU for the current cycle.
   */
  struct bus {
    /**
     * Address currently presented on the CPU address bus.
     */
    uword addr;

    /**
     * Value transferred on the CPU data bus.
     */
    ubyte val;

    /**
     * Indicates whether the current bus operation is a write.
     *
     * A value of true represents a CPU write operation; false represents
     * a CPU read operation.
     */
    bool write;
  } bus;

  /**
   * Current instruction execution state.
   */
  struct instr {
    /**
     * Effective address associated with the current instruction.
     */
    uword addr;

    /**
     * Temporary pointer used during address calculation.
     */
    uword ptr;

    /**
     * Indicates whether the instruction address has been fetched.
     */
    bool addr_fetched;

    /**
     * Current cycle within instruction execution.
     */
    byte step;

    /**
     * Opcode currently being executed.
     */
    ubyte opcode;
  } instr;

  /**
   * CPU reset state.
   */
  struct reset {
    /**
     * Current cycle within the reset sequence.
     */
    ubyte step;

    /**
     * Indicates that a reset sequence is pending.
     */
    bool pending;
  } reset;

  /**
   * CPU interrupt state.
   */
  struct interrupt {
    /**
     * Indicates that BRK processing has started.
     */
    bool breakStarted;

    /**
     * Indicates that a non-maskable interrupt is pending.
     */
    bool nmiPending;

    /**
     * Current level of the maskable IRQ input line.
     *
     * A value of true represents an asserted IRQ line.
     */
    bool irqLine;

    /**
     * Current cycle within interrupt processing.
     */
    byte step;
  } interrupt;

  /**
   * OAM DMA transfer state.
   *
   * Represents the CPU-side state of a $4014 OAM DMA operation.
   */
  struct oamdma {
    /**
     * Indicates whether OAM DMA is currently active.
     */
    bool active;

    /**
     * Current cycle within the OAM DMA sequence.
     */
    word step;

    /**
     * Current CPU memory address involved in the DMA transfer.
     */
    uword addr;
  } oamdma;

  /**
   * Indicates that the CPU has entered a permanently halted state.
   *
   * This is used for illegal/JAM opcodes that halt normal processor
   * execution.
   */
  bool jammed;
} CPU_6502;

/**
 * Advance the CPU by one clock cycle.
 *
 * Executes one cycle of CPU operation using the current CPU state and
 * updates the processor registers, internal execution state, and bus
 * state for the next cycle.
 *
 * Memory accesses requested by the CPU are represented through the
 * CPU_6502::bus structure and are handled by the surrounding memory
 * system.
 */
void clock_cpu_6502(CPU_6502 *c);

#endif // NES_6502_H
